const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(__dirname+'/trading_ui.html','utf8'),script=html.match(/<script>([\s\S]*?)<\/script>/)[1];new vm.Script(script);
const block=script.slice(script.indexOf('// Stock paper accounts:')).replace('stockRefresh();setInterval(stockRefresh,15000);','');
const nodes={},tables={};let fail=false;
const account={id:'trend_5m',label:'Trend',interval:'5m',initial:25000,equity:24999,cash:20000,pnl:-1,observation_count:3,fill_count:1,matched_observations:3,matched_record:false,return_pct:-0.004,benchmark_return_pct:null,excess_return_pct:null};
const payload={accounts:[account],capital:150000,reference_capital:50000,basket:['SPY'],paused:false,busy:false,interval_status:{5:'Closed'},notes:['No leverage'],cost_bps_per_side:6};
const ctx={Number,Date,console,encodeURIComponent,setInterval(){},document:{createElement(){return {}}},el(id){return nodes[id]??={value:'',append(){},replaceChildren(){}}},money:n=>String(n),fill(id,headers,rows){tables[id]=rows},post:async()=>({}),fetch:async()=>{if(fail)throw Error();return {ok:true,json:async()=>payload}}};
vm.createContext(ctx);vm.runInContext(block,ctx);
(async()=>{await ctx.stockRefresh();assert(tables['stock-accounts'][0].slice(-3).every(x=>x==='Not enough matching data'));assert.match(nodes['stock-capital'].textContent,/150000/);account.matched_record=true;account.benchmark_return_pct=1;account.excess_return_pct=-1.004;await ctx.stockRefresh();assert.equal(tables['stock-accounts'][0].at(-1),'-1.00 pp');fail=true;await ctx.stockRefresh();assert.match(nodes['stock-message'].textContent,/stale/);assert.equal(nodes['stock-check'].disabled,true);console.log('PASS shipped UI syntax, capital separation, mismatched evidence suppression, matched comparison, disconnect warning')})().catch(e=>{console.error(e);process.exit(1)});
